name: Github Actions Demo
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Danger 
        run: npx -y danger ci
