name: Github Actions Demo
on: pull_request
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    name: Danger
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Danger 
        if: ${{ github.event_name == 'pull_request' }}
        run: npx -y danger ci --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
