name: Github Actions Demo
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Hello world step
        uses: .github/actions/lint
        with:
          who-to-greet: 'Mona the Octocat'
