name: Github Actions Demo
on: pull_request
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    name: Danger
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install eslint @actions/core @actions/github --no-save
      - name: Danger
        if: ${{ github.event_name == 'pull_request' }}
        run: npx -y danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
